trigger:
- main   # or your branch name

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'   # or your Node version
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build --if-present
    npm test
  displayName: 'Install dependencies, build, and test'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/test-results.xml'
    failTaskOnFailedTests: true
  condition: succeededOrFailed()
